# Site settings
title: Ayoung Notes
description: "Decentralization Enthusiast| Local Innovation Startup| Life Coaching|"
url:  "https://yamt.netlify.app" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Saing Sab (Ayoung)"
  email: "saing.sab@gmail.com"
  url: "https://ayoungnotes.com"
permalink: /:year/:month/:day/:title:output_ext

#Theme
theme: jekyll-yamt
#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
twitter:
  username: saingsab
  card: summary
facebook:
  app_id: # Facebook app ID for Facebook insights
  publisher: # Facebook page URL or ID of the publishing entity
  admins: # Facebook user ID for domain insights linked to a personal account
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://twitter.com/saingsab
    - https://www.github.com/saingsab
    - https://www.linkedin.com/in/saingsab
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never